services:
  - type: web
    name: auto-pilot-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    rootDirectory: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: DEBUG
        value: "app:*"
